name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.http://138.197.33.231}}
          username: ${{ secrets.root}}
          key: ${{ secrets.ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIjaQguMY2VgIBJwVs7YfkgYbNUpuaZjeV/EpBX3H9UN https://trackmyhomeschool.com}}
          script: |
            /root/trackSchool/deploy.sh
